version: '3'
services:
  nginx:
    container_name: cs3_nginx
    image: nginx:cateringservice3_${BUILD_ID}
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  php:
    container_name: cs3_php
    image: php:cateringservice3_${BUILD_ID}
    build: php
    restart: always
    tty: true
    ports:
      - "9000:9000"
