version: '3'
services:
  nginx:
    container_name: cs3_nginx
    image: nginx:${BUILD_ID}_${GIT_COMMIT}
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: cs3_php
    image: php:${BUILD_ID}_${GIT_COMMIT}
    build: php
    restart: always
    tty: true
    ports:
      - "9000:9000"
