version: '3'
services:
  nginx:
    image: cs3_nginx:v${BUILD_ID}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  php:
    image: cs3_php:v${BUILD_ID}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
    ports:
      - "9000:9000"
